# Generated by Django 2.0.3 on 2018-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('word', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=32)),
            ],
        ),
    ]
